### ISSUE TITLE
trickle down to SVG plots

### ISSUE THREAD

**Issue by bjarthur** [JunoLab/Juno.jl#125]
Gadfly has [zoom/pan functionality](http://gadflyjl.org/latest/tutorial.html#Interactivity-1) included in it's SVG plots (via javascript) which is much nicer than that provided by the Atom GUI.  the problem is that events are not trickled down to the plot, but are captured by Atom.  is there a way to change this?  thanks.

**Comment by bjarthur** [comment]
@MikeInnes can you perhaps give me a pointer to resolving this issue?  would be great to have better Gadfly support in Atom.  thanks.

**Comment by pfitzseb** [comment]
This is definitely possible, but our API for it isn't very nice. I'll try to come up with something nicer than we have right now.
You could handle it [like Plotlyjs.jl](https://github.com/sglyon/PlotlyJS.jl/blob/c9b8abca957e9d84326c609ba3b9d2b001d1147a/src/displays/electron.jl), but that seems like overkill for something that should be simpler.

**Comment by pfitzseb** [comment]
Changing Gadfly's `render` method to 
```
import Juno: Juno, @render, media, Media

media(Plot, Media.Plot)

function Juno.render(pp::Juno.PlotPane, p::Plot)
    x, y = Juno.plotsize()
    set_default_plot_size(x*Gadfly.px, (y-1)*Gadfly.px)
    w = Juno.Atom.blinkplot()
    Juno.Atom.Blink.body!(w, HTML(stringmime("text/html", p)))
end
```
works (mostly) well:
![gadfly](https://user-images.githubusercontent.com/6735977/38314246-0ba49108-3826-11e8-8ace-2d1e15c0fe36.png)

Two problems with that right now:
1. Accessing `Juno.Atom` and `Juno.Atom.Blink` is kinda unfortunate. Obviously solvable with a better API.
2. The `Next Plot`/`Previous Plot` buttons break display. This is a bit tricky to get right, unfortunately.

**Comment by bjarthur** [comment]
it's beautiful, thank you!

do you want to make a PR to Gadfly with this as is?  or would you prefer to wait for a better API, and a way to fix the next/prev plot buttons?

this would've taken me months to figure out, so again, thanks!

**Comment by bjarthur** [comment]
we're hoping to [tag gadfly](https://github.com/GiovineItalia/Gadfly.jl/issues/1140) soon.  i would love to include better support for Atom.  is there by chance an easy fix for the next/prev buttons?

**Comment by pfitzseb** [comment]
Probably not, but I'll look into it again.

I'm rather busy with 0.7 compatibility at the moment, so no promises :)

**Comment by pfitzseb** [comment]
Ok, this is trivial on Juno 0.7 with Julia 0.7 (just define a `show` method for `MIME"image/svg+xml"`).
Closing.

**Comment by bjarthur** [comment]
still can't get Gadfly interactivity to work in Juno.  [here](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/Gadfly.jl#L946) is where `show(io::IO, m::MIME"image/svg+xml", p::Plot)` is defined.  it was actually already there for a long time.  if i change `SVG` to `SVGJS` in that function definition, which is what enables the interactivity, i can not zoom or pan in atom using julia 7.0, Atom 0.7.5, Juno 0.5.2, etc.  can you give me a hint how to fix it?  thanks.

maybe it has something to do [with these lines](https://github.com/GiovineItalia/Gadfly.jl/blob/master/src/Gadfly.jl#L1096)?  for the time being i have deleted them in my local installation as they were causing a warning:

```
WARNING: eval from module Media to Gadfly:    
Expr(:where, Expr(:call, Expr(:., :Media, :(:media)), Expr(:::, Expr(:curly, :Type, :T))), Expr(:<:, :T, Gadfly.Plot)) = Expr(:block, #= Symbol("/Users/arthurb/.julia/dev/Media/src/system.jl"):71 =#, Expr(:ref, Array{Any, (1,)}[Media.Plot], 1))
```

**Comment by pfitzseb** [comment]
I think you can remove all Juno specifc code from Gadfly and it *should* work.

**Comment by bjarthur** [comment]
i did, and it doesn't.  :(

**Comment by pfitzseb** [comment]
Ah I see, that's related to https://github.com/JunoLab/atom-julia-client/issues/497. Should be fixed with https://github.com/JunoLab/Atom.jl/commit/1247525879601f128264d655d38f49ffef810981.

Regardless of that commit you could also define a `show` method for `MIME"application/juno+plotpane ` and print a svg data url there. That'll guarantee that Juno's interactivity is disabled.

**Comment by bjarthur** [comment]
still doesn't work.

defining a MIME"application..." opens the plot in the default web browser, and the interactivity works there of course, but not ideal because it doesn't use the Atom plot panel.

checking out master of Atom and changing the existing MIME"image/svg+xml" to embed javascript puts the plot in Atom.  and while Atom's zoom/pan buttons are now not displayed, the plot's are not enabled.

anything else i should try?  thanks.

**Comment by pfitzseb** [comment]
> defining a MIME"application..." opens the plot in the default web browser, and the interactivity works there of course, but not ideal because it doesn't use the Atom plot panel.

That definitely shouldn't happen (and doesn't for me with e.g. the example in the Juno docs).

> checking out master of Atom and changing the existing MIME"image/svg+xml" to embed javascript puts the plot in Atom. and while Atom's zoom/pan buttons are now not displayed, the plot's are not enabled.

Not sure what's going on there then. I can't really figure out how to get Gadfly running on 0.7 though (on `Gadfly#bjarthur:bja/julia07`, `Compose#tn/more-v07-fixes` and IndirectArrays master).

**Comment by bjarthur** [comment]
oh, wow, thanks for trying to get gadfly working.  probably easiest for you to wait until that Compose PR is merged, as there's lot's of fixes that haven't been pushed to github yet.  let me get back to you when we are more ready for you help.  thanks!

**Comment by tlnagy** [comment]
@pfitzseb Now that both `Compose#master` and the latest `Hexagons` release support Julia 1.0, could you give this another look? It should be as easy as checking out `Gadfly#bja/julia07`, `Compose#master` and doing a Pkg update.

**Comment by pfitzseb** [comment]
Ok, this is weird. I'm getting 
```
Uncaught SyntaxError: Unexpected number
Uncaught SyntaxError: Unexpected end of input
```
from the plot pane, apparently triggered by the first `fill="#000000"` statement in the code.

I couldn't yet figure out what's going wrong here.

We could probably work around this by saving the svg to disk and loading that, much like what happens when the plot is opened in a browser, but I'd still like to find out what's going on here.

**Comment by pfitzseb** [comment]
Fixed now.
