### ISSUE TITLE
Julia 0.7

### ISSUE THREAD

**Issue by MikeInnes** [JunoLab/Juno.jl#127]
Tracking what we need for this right now. With the following patches I have Atom.jl compiling but there are some internal errors for various things.

Current setup:
```
git clone -b julia-0.7 https://github.com/JunoLab/atom-julia-client
cd atom-julia-client
apm install
apm link
cd ..
git clone -b 0.9 https://github.com/JunoLab/atom-ink
cd atom-ink
apm install
apm link
# in Pkg mode:
add Juno#julia-0.7 CodeTools#julia-0.7 Atom#julia-0.7 https://github.com/pfitzseb/TreeViews.jl
```

If you want to keep using Juno with Julia 0.6 then replace the `apm link` lines above with `apm link -d` and start Atom with `atom -d`.

You probably also want to turn off depwarns in the julia-client settings.

Items to fix:
* [x] Occasional errors indexing into docstrings
* [x] Updates for Requires
* [x] Major load time regression (`@time using Atom` went from ~13s to ~35s on my laptop, even though Blink.jl isn't loaded anymore)
* [ ] Package commands need to be updated for pkg3
* [ ] ASTInterpreter2.jl compat for Traceur.jl integration and debugger
* [x] StringDistances.jl fixes so docpane search works properly

**Comment by MikeInnes** [comment]
I quite often see hangs when booting Juno lately, but they seem to be exacerbated on 0.7:

```julia
julia> using Atom
^CERROR: InitError: InterruptException:
Stacktrace:
 [1] process_events at ./libuv.jl:82 [inlined]
 [2] wait() at ./event.jl:258
 [3] wait(::Condition) at ./event.jl:46
 [4] _require(::Base.PkgId) at ./loading.jl:934
  ...
```

**Comment by pfitzseb** [comment]
> patching Juno.jl fixes this particular issue, although there appear to be other hangs on boot.

Yeah, without that patch you can't load Atom in a REPL. Not entirely sure why that happens, but it's probably related to the code loading changes on 0.7.

**Comment by MikeInnes** [comment]
Yeah, I think there must be a `using Atom` lock somewhere that we try to use twice. I guess that's not related to other hangs I've seen, but I'll try to get a stacktrace for one of those.

**Comment by MikeInnes** [comment]
Here's one:
```
julia> ERROR: InterruptException:
Stacktrace:
 [1] process_events at ./libuv.jl:82 [inlined]
 [2] wait() at ./event.jl:258
 [3] wait(::Condition) at ./event.jl:46
 [4] wait_readnb(::Base.TTY, ::Int64) at ./stream.jl:301
 [5] eof(::Base.TTY) at ./stream.jl:61
 [6] eof(::REPL.Terminals.TTYTerminal) at ./io.jl:272
 [7] match_input(::Dict{Char,Any}, ::REPL.LineEdit.MIState, ::REPL.Terminals.TTYTerminal, ::Array{Char,1}, ::Dict{Char,Any}) at /Users/mike/projects/julia/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:1287 (repeats 2 times)
 [8] prompt!(::REPL.Terminals.TTYTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/mike/projects/julia/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:2299
 [9] run_interface(::REPL.Terminals.TTYTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/mike/projects/julia/usr/share/julia/site/v0.7/REPL/src/LineEdit.jl:2208
 [10] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /Users/mike/projects/julia/usr/share/julia/site/v0.7/REPL/src/REPL.jl:1025
 [11] run_repl(::REPL.LineEditREPL, ::getfield(Base, Symbol("##683#685"))) at /Users/mike/projects/julia/usr/share/julia/site/v0.7/REPL/src/REPL.jl:187
 [12] (::getfield(Base, Symbol("##682#684")){Bool,Bool,Bool,Bool})(::Module) at ./client.jl:414
 [13] (::getfield(Base, Symbol("#inner#4")){Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},getfield(Base, Symbol("##682#684")){Bool,Bool,Bool,Bool},Tuple{Module}})() at ./essentials.jl:643
 [14] #invokelatest#3 at ./essentials.jl:644 [inlined]
 [15] invokelatest at ./essentials.jl:643 [inlined]
 [16] run_main_repl(::Bool, ::Bool, ::Bool, ::Bool, ::Bool) at ./client.jl:398
 [17] exec_options(::Base.JLOptions) at ./client.jl:338
 [18] _start() at ./client.jl:455
```

**Comment by pfitzseb** [comment]
Ok, from some superficial testing I couldn't find any more errors, just lots of deprecation warnings... Will look into fixing those soon.

So far I didn't notice any hangs on startup -- might be OS specific or something (I was only testing on Linux)?

**Comment by dlfivefifty** [comment]
Any news on timeline for this? 

With v0.7-alpha out and it being time to update packages, having Juno would make this task a lot easier.

**Comment by pfitzseb** [comment]
I'll take another look at this in the next couple of days. Once the necessary refactoring and fixes are done we can switch master of the Julia packages to 0.7 and maybe even release a preliminary version.

**Comment by andylamp** [comment]
@MikeInnes Juno, specifically `julia-client`, fails on MacOS when used in conjuction with `0.7` -- with `0.6` everything works as it should.

full traceback is attached below

```
┌ Warning: `shift!` is deprecated, use `popfirst!` instead.
│   caller = top-level scope at boot_repl.jl:2
└ @ Core boot_repl.jl:2
WARNING: Base.STDERR is deprecated, use stderr instead.
  likely near /Users/andylamp/.atom/packages/julia-client/script/boot_repl.jl:15
juno-msg-loadERROR: LoadError: ArgumentError: Module Atom not found in current path.
Run `Pkg.add("Atom")` to install the Atom package.
Stacktrace:
 [1] require(::Module, ::Symbol) at ./loading.jl:868
 [2] top-level scope at /Users/andylamp/.atom/packages/julia-client/script/boot_repl.jl:7
 [3] include at ./boot.jl:314 [inlined]
 [4] include_relative(::Module, ::String) at ./loading.jl:1071
 [5] include(::Module, ::String) at ./sysimg.jl:29
 [6] exec_options(::Base.JLOptions) at ./client.jl:267
 [7] _start() at ./client.jl:427
in expression starting at /Users/andylamp/.atom/packages/julia-client/script/boot_repl.jl:16

Julia has exited. Press Enter to start a new session.
```

**Comment by pfitzseb** [comment]
> We should also figure out how Juno should install itself in a Pkg3 world. I think we should be making a Juno-specific environment and stacking it on top of the primary one.

Yep, makes sense. Should probably wait with that until all packages are Pkg3ified.

@andylamp Do you actually have Atom.jl installed and checked out the correct branches mentioned in the first post? You'll also need to checkout julia-client master, I think.

**Comment by andylamp** [comment]
@pfitzseb I have the latest ones available in the package directory, I was under the impression that these changes were pushed as there was an update -- if not I'll revert to `0.6` for now.

**Comment by pfitzseb** [comment]
No, they were not. Juno doesn't officially support Julia 0.7 yet.

**Comment by pfitzseb** [comment]
Pretty sure you don't have to mess with the Atom packages at all right now (I've pushed something similar to the fixed boot script to julia-client#master).

**Comment by marcpabst** [comment]
I followed the instructions provided in the first post but I still get `ERROR: LoadError: UndefVarError: find_in_path not defined`.

**Comment by tlienart** [comment]
@marcpabst FWIW, I managed to get it to "work" following part of mike's instructions. 

In Julia 7 terminal: 
* `]` to get in package mode
* `add Juno#julia-0.7 CodeTools#julia-0.7 Atom#julia-0.7`
* (quit)

In Atom, in package settings -> change `Julia-0.6` to `Julia-0.7` in the Julia Path

Then I started the REPL, it threw a load of deprecation warnings at me (`Lazy.jl`, `Nullable.jl`, `IterTools.jl`, `DocSeeker`) but no errors. 

That gets you to a working REPL that will throw a deprecation warning at every line you run:

<img width="667" alt="screen shot 2018-06-18 at 10 02 55" src="https://user-images.githubusercontent.com/10897531/41513398-eb024582-72de-11e8-9b5b-24d3f1f12889.png">

So I think I'll wait a bit and keep developing in 0.6.3 for now 👅 ... 

FWIW, here's my `versioninfo()` 

```
Julia Version 0.7.0-alpha.0
Commit 22590d529d (2018-05-31 00:07 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_SVG_BROWSER = Opera.app
  JULIA_NUM_THREADS = 2
```

**Comment by marcpabst** [comment]
@tlienart thanks - I will try it ASAP. I kinda switched to VS Code (which I already had installed and overall feels much snappier) but I really miss the workspace explorer.

**Comment by pfitzseb** [comment]
Turns out I forgot to push the fix for those depwarns -- should be fixed with the latest commit to `Atom.jl#julia-0.7`.

**Comment by tlienart** [comment]
It does, thanks.

FWIW, killing and starting a REPL is much slower with 0.7 than with 0.6.3 (with 0.6 it's almost instantaneous, with 0.7 ~1-2 seconds). This may just be the DepWarns.

```
julia> versioninfo()
Julia Version 0.7.0-alpha.0
Commit 22590d529d (2018-05-31 00:07 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_SVG_BROWSER = Opera.app
  JULIA_NUM_THREADS = 2
```

**Comment by marius311** [comment]
Figured I'd post here rather than separate issue. Is it just me or does the 0.7 branch only evaluate things in `Main`, despite the "currently working in module XXX" suggesting otherwise? E.g.

![image](https://user-images.githubusercontent.com/1510968/41814761-a2202afa-7757-11e8-9222-74686e0f530b.png)

With the cursor on the  `@__MODULE__` line, note the "Main/foo" in the bottom right corner which looks right, but evaluating the line gives `Main` instead of `Main.foo` like I'd expect. Any ideas?

**Comment by pfitzseb** [comment]
Yeah, sorry about that -- should be fixed with https://github.com/JunoLab/CodeTools.jl/commit/8653e3fd84517668a6c284b223c61eb4debf3777.

**Comment by marius311** [comment]
Sorry maybe I screwed something up updating but it doesn't seem to work for me, I get the same exact thing as above. Fyi, I have, 

```
(v0.7) pkg> st
    Status `~/.julia/environments/v0.7/Project.toml`
  [621f4979] AbstractFFTs v0.3.1
  [c52e3926] Atom v0.6.14+ #julia-0.7 [https://github.com/JunoLab/Atom.jl.git]
  [6e4b80f9] BenchmarkTools v0.3.1
  [ad839575] Blink v0.6.2
  [53a63b46] CodeTools v0.5.0+ #julia-0.7 [https://github.com/JunoLab/CodeTools.jl.git]
  [c3611d14] ColorVectorSpace v0.5.2
  [2b5f629d] DiffEqBase v3.12.1
  [7a1cc6ca] FFTW v0.2.2
  [58cfbd8c] HttpServer v0.3.1+ #julia-0.7 [https://github.com/JuliaWeb/HttpServer.jl.git]
  [916415d5] Images v0.14.0
  [a98d9a8b] Interpolations v0.7.3
  [033835bb] JLD2 v0.0.6
  [e5e0dc1b] Juno v0.4.1+ #julia-0.7 [https://github.com/JunoLab/Juno.jl.git]
  [50d2b5c4] Lazy v0.12.1
  [1914dd2f] MacroTools v0.4.1
  [e89f7d12] Media v0.4.0
  [15e1cf62] NPZ v0.2.0
  [c030b06c] ODE v1.0.0
  [429524aa] Optim v0.15.1+ #v07compat [https://github.com/JuliaNLSolvers/Optim.jl.git]
  [d96e819e] Parameters v0.9.0
  [92933f4c] ProgressMeter v0.5.5
  [438e738f] PyCall v1.17.1
  [d330b81b] PyPlot v2.5.0
  [276daf66] SpecialFunctions v0.5.0
  [90137ffa] StaticArrays v0.7.2
  [2913bbd2] StatsBase v0.23.0
  [0796e94c] Tokenize v0.5.0
```

I don't know how it works in Pkg3 to verify I'm on the right commit in CodeTools but I went in in `~/.julia/packages/CodeTools/7L2s/src/eval.jl` and checked by hand that its on the commit you specified above. Otherwise I'm on julia-client:aa133bc.

**Comment by pfitzseb** [comment]
Hm, maybe this actually got fixed in the commit after that which I forgot to push until now. For me it looks like this now:
![image](https://user-images.githubusercontent.com/6735977/41848246-11c92656-787d-11e8-9a64-e11277b0d528.png)

Things are still kinda wonky wrt to choosing modules to eval in, but I hope to have this fixed properly soon.

**Comment by marius311** [comment]
Yep I think that did it, many thanks!

**Comment by Datseris** [comment]
@pfitzseb I followed the steps you mentioned, so that I can have the atom development mode to run on Julia 0.7, but it didn't work:
```
Press Enter to start Julia.
ERROR: LoadError: UndefVarError: popfirst! not defined
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:576
 [2] include(::String) at .\sysimg.jl:14
 [3] process_options(::Base.JLOptions) at .\client.jl:305
 [4] _start() at .\client.jl:371
while loading C:\Users\datseris\Juno07\atom-julia-client\script\boot_repl.jl, in expression starting
 on line 2
```

**Comment by marius311** [comment]
I think you're accidentally using Julia 0.6, maybe check that the executable you've specific in julia-client settings is an 0.7 one?

**Comment by Datseris** [comment]
Yeap, I had to link new version. However... I actually does not work as pfitzeb "promised"  :D 

The link to which Julia version is saved between `atom` and `atom -d` . So this means each time I want to switch versions I have to change this path, and re-open atom .

**Comment by marius311** [comment]
Yea I had a similar feature request, basically the ability to quickly choose which version of Julia to boot up, kind of like choosing Jupyter kernels, although its not all that critical. Btw, you don't need to restart Atom, you can just change the Julia version then kill / restart the Julia kernel.

**Comment by ChrisRackauckas** [comment]
I'm getting an error in Lazy.jl:

```julia
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0-beta.94 (2018-06-30 01:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 459281628d (5 days old master)
|__/                   |  x86_64-w64-mingw32

julia> using Atom
[ Info: Precompiling module Atom
┌ Warning: `foldr(op, v0, itr)` is deprecated, use `foldr(op, itr; init=v0)` instead.
│   caller = @match(::LineNumberNode, ::Module, ::Any, ::Any) at macro.jl:54
└ @ MacroTools macro.jl:54
ERROR: LoadError: LoadError: LoadError: UndefVarError: dims not defined
Stacktrace:
 [1] reduce(::Function, ::Symbol, ::Tuple{Expr,Expr}) at .\deprecated.jl:54
 [2] (::getfield(Lazy, Symbol("#thread#4")))(::Symbol, ::Expr, ::Expr) at C:\Users\Chris\.julia\packages\Lazy\fdVy\src\macros.jl:118
 [3] @>>(::LineNumberNode, ::Module, ::Vararg{Any,N} where N) at C:\Users\Chris\.julia\packages\Lazy\fdVy\src\macros.jl:120
 [4] include at .\boot.jl:317 [inlined]
 [5] include_relative(::Module, ::String) at .\loading.jl:1034
 [6] include at .\sysimg.jl:29 [inlined]
 [7] include(::String) at C:\Users\Chris\.julia\packages\Lazy\fdVy\src\Lazy.jl:3 [8] top-level scope at none:0
 [9] include at .\boot.jl:317 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1034
 [11] include(::Module, ::String) at .\sysimg.jl:29
 [12] top-level scope at none:0
 [13] eval at .\boot.jl:319 [inlined]
 [14] eval(::Expr) at .\client.jl:394
 [15] top-level scope at .\none:3 [inlined]
 [16] top-level scope at .\<missing>:0
in expression starting at C:\Users\Chris\.julia\packages\Lazy\fdVy\src\tail.jl:26
in expression starting at C:\Users\Chris\.julia\packages\Lazy\fdVy\src\tail.jl:26
in expression starting at C:\Users\Chris\.julia\packages\Lazy\fdVy\src\Lazy.jl:13
ERROR: LoadError: Failed to precompile Lazy to C:\Users\Chris\.julia\compiled\v0.7\Lazy\mi7U.ji.
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] compilecache(::Base.PkgId) at .\loading.jl:1164
 [3] _require(::Base.PkgId) at .\loading.jl:938
 [4] require(::Base.PkgId) at .\loading.jl:838
 [5] require(::Module, ::Symbol) at .\loading.jl:833
 [6] include at .\boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1034
 [8] include(::Module, ::String) at .\sysimg.jl:29
 [9] top-level scope at none:0
 [10] eval at .\boot.jl:319 [inlined]
 [11] eval(::Expr) at .\client.jl:394
 [12] top-level scope at .\none:3 [inlined]
 [13] top-level scope at .\<missing>:0
in expression starting at C:\Users\Chris\.julia\packages\Atom\HsuW\src\Atom.jl:5ERROR: Failed to precompile Atom to C:\Users\Chris\.julia\compiled\v0.7\Atom\w9XO.ji.
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] compilecache(::Base.PkgId) at .\loading.jl:1164
 [3] _require(::Base.PkgId) at .\loading.jl:966
 [4] require(::Base.PkgId) at .\loading.jl:838
 [5] require(::Module, ::Symbol) at .\loading.jl:833

(v0.7) pkg> dev Lazy
   Cloning git-repo `https://github.com/MikeInnes/Lazy.jl.git`
  Updating git-repo `https://github.com/MikeInnes/Lazy.jl.git`
┌ Warning: packages will need to have a [Julia]Project.toml file in the future
└ @ Pkg.Types Types.jl:578
 Resolving package versions...
┌ Warning: julia version requirement for package PackageSpec("RandomNumbers", UUID("e6cf234a-135c-5ec9-84dd-332b85af5143"), v"0.1.1+") not satisfied
└ @ Pkg.Operations Operations.jl:165
  Updating `C:\Users\Chris\.julia\environments\v0.7\Project.toml`
  [50d2b5c4] + Lazy v0.12.1+ [`C:\Users\Chris\.julia\dev\Lazy`]
  Updating `C:\Users\Chris\.julia\environments\v0.7\Manifest.toml`
  [50d2b5c4] ↑ Lazy v0.12.1 ⇒ v0.12.1+ [`C:\Users\Chris\.julia\dev\Lazy`]

julia> using Atom
[ Info: Precompiling module Atom
┌ Warning: `foldr(op, v0, itr)` is deprecated, use `foldr(op, itr; init=v0)` instead.
│   caller = @match(::LineNumberNode, ::Module, ::Any, ::Any) at macro.jl:54
└ @ MacroTools macro.jl:54
ERROR: LoadError: LoadError: LoadError: UndefVarError: dims not defined
Stacktrace:
 [1] reduce(::Function, ::Symbol, ::Tuple{Expr,Expr}) at .\deprecated.jl:54
 [2] (::getfield(Lazy, Symbol("#thread#4")))(::Symbol, ::Expr, ::Expr) at C:\Users\Chris\.julia\dev\Lazy\src\macros.jl:118
 [3] @>>(::LineNumberNode, ::Module, ::Vararg{Any,N} where N) at C:\Users\Chris\.julia\dev\Lazy\src\macros.jl:120
 [4] include at .\boot.jl:317 [inlined]
 [5] include_relative(::Module, ::String) at .\loading.jl:1034
 [6] include at .\sysimg.jl:29 [inlined]
 [7] include(::String) at C:\Users\Chris\.julia\dev\Lazy\src\Lazy.jl:3
 [8] top-level scope at none:0
 [9] include at .\boot.jl:317 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1034
 [11] include(::Module, ::String) at .\sysimg.jl:29
 [12] top-level scope at none:0
 [13] eval at .\boot.jl:319 [inlined]
 [14] eval(::Expr) at .\client.jl:394
 [15] top-level scope at .\none:3 [inlined]
 [16] top-level scope at .\<missing>:0
in expression starting at C:\Users\Chris\.julia\dev\Lazy\src\tail.jl:26
in expression starting at C:\Users\Chris\.julia\dev\Lazy\src\tail.jl:26
in expression starting at C:\Users\Chris\.julia\dev\Lazy\src\Lazy.jl:13
ERROR: LoadError: Failed to precompile Lazy to C:\Users\Chris\.julia\compiled\v0.7\Lazy\mi7U.ji.
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] compilecache(::Base.PkgId) at .\loading.jl:1164
 [3] _require(::Base.PkgId) at .\loading.jl:938
 [4] require(::Base.PkgId) at .\loading.jl:838
 [5] require(::Module, ::Symbol) at .\loading.jl:833
 [6] include at .\boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at .\loading.jl:1034
 [8] include(::Module, ::String) at .\sysimg.jl:29
 [9] top-level scope at none:0
 [10] eval at .\boot.jl:319 [inlined]
 [11] eval(::Expr) at .\client.jl:394
 [12] top-level scope at .\none:3 [inlined]
 [13] top-level scope at .\<missing>:0
in expression starting at C:\Users\Chris\.julia\packages\Atom\HsuW\src\Atom.jl:5
ERROR: Failed to precompile Atom to C:\Users\Chris\.julia\compiled\v0.7\Atom\w9XO.ji.
Stacktrace:
 [1] error at .\error.jl:33 [inlined]
 [2] compilecache(::Base.PkgId) at .\loading.jl:1164
 [3] _require(::Base.PkgId) at .\loading.jl:966
 [4] require(::Base.PkgId) at .\loading.jl:838
 [5] require(::Module, ::Symbol) at .\loading.jl:833
```

**Comment by marius311** [comment]
That was fixed in https://github.com/JuliaLang/julia/pull/27884 I think. I can't speak for current master but the commit which merged that PR works for me.

**Comment by ChrisRackauckas** [comment]
I see. The nightlies work but the beta build doesn't.

**Comment by beOn** [comment]
Wait... damn. That was after I edited user.jl to use Main.Atom() instead of simply Atom(). Without that change, Atom is still undefined.

**Comment by Datseris** [comment]
After installing and actually having Juno run julia 0.7, I always get the "Windows error sound" whenever I click anywhere in Atom. It is extremely annoying, I can't stand it...

**Comment by pfitzseb** [comment]
@Datseris Can you open the electron console  (Ctrl-Shift-I) and report any errors you might find there?

**Comment by Datseris** [comment]
Sorry Sebastian, I will not have time to do this for quite a while (I have removed Juno from 0.7 because I need to work on more pressing matters). If it is not solved when I have time again, I will report here.

**Comment by pfitzseb** [comment]
Sure, sounds good :)

**Comment by pfitzseb** [comment]
PSA: You now need ink on the `0.9` branch.

**Comment by Datseris** [comment]
On a side note, is there any plan to also support the amazing, spectacular, much better "Legacy Style" console in Juno when it moves to Julia 0.7/1.0?

*Disclaimer: this post is full of my own opinions :D*

**Comment by pfitzseb** [comment]
No, afraid not. It might continue to somewhat work by accident, but I definitely wouldn't recommend using it.

**Comment by gpapo** [comment]
Hi, I don't know if it is correct to post this here or to open a new issue. I have followed the instructions on the first post and installed julia-v0.7 but got this error trying to `using DataFrames`
```julia
julia> using DataFrames
ERROR: MethodError: no method matching shouldlog(::Atom.Progress.JunoProgressLogger, ::Base.CoreLogging.LogLevel, ::Module, ::Symbol, ::Symbol)
The applicable method may be too new: running in world age 27561, while current world is 27582.
Closest candidates are:
  shouldlog(::Atom.Progress.JunoProgressLogger, ::Any, ::Any, ::Any, ::Any) at /home/giovanni/.julia/packages/Atom/RoGy/src/progress.jl:67 (method too new to be called from this world context.)
  shouldlog(::Base.CoreLogging.NullLogger, ::Any...) at logging.jl:83
  shouldlog(::Base.CoreLogging.SimpleLogger, ::Any, ::Any, ::Any, ::Any) at logging.jl:507
  ...

julia> versioninfo()
Julia Version 0.7.0-beta2.0
Commit b145832402* (2018-07-13 19:54 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, sandybridge)
Environment:
  JULIA_EDITOR = atom -a
  JULIA_NUM_THREADS = 2

```

**Comment by stakaz** [comment]
I was able to run Juno in Atom following the instructions. However, after a first error while running a code block or line, I do not get any further output in the REPL. After a restart of julia it starts to work again. Does anyone else has such issues?

**Comment by pfitzseb** [comment]
That sounds weird -- can you show a gif of what's happening?

**Comment by stakaz** [comment]
Ok, after restarting several times it looks like it  works as expected. Will post, if I will see this behavior again...

**Comment by pfitzseb** [comment]
It does, thanks! Fixed with https://github.com/JunoLab/Atom.jl/commit/d222dcaa8db486c324da432d855b92e7abf041b1, so `pkg> up` and you should be good to go.

**Comment by marius311** [comment]
Lately I can't seem to get inline evaluations to work at all, it just hangs forever. If I interrupt, Julia dies with the following trace:

```
fatal: error thrown and no exception handler available.
InterruptException()
jl_run_once at /home/marius/src/julia/src/jl_uv.c:185
process_events at ./libuv.jl:94 [inlined]
wait at ./event.jl:246
task_done_hook at ./task.jl:307
jl_apply_generic at /home/marius/src/julia/src/gf.c:2151
jl_apply at /home/marius/src/julia/src/julia.h:1532 [inlined]
finish_task at /home/marius/src/julia/src/task.c:233
start_task at /home/marius/src/julia/src/task.c:276
unknown function (ip: 0xffffffffffffffff)

Julia has exited. Press Enter to start a new session.
```

This is julia 656d58782c, Atom 1.28.2, ink 0.9, julia-client 2c7bb14, Juno eb48da0, Atom d222dca, CodeTools 3f75083. 

Anyone else seeing this?

**Comment by stakaz** [comment]
For me it works after the fix.

**Comment by marius311** [comment]
Ah, nevermind, I think I hadn't correctly updated Atom to d222dca. However, I can't figure out how to install this latest version, I keep getting errors about the TreeViews dep not being found. I tried to add it by hand with `add github.com/.../TreeViews.jl` but now I get eg:

```
(v0.7) pkg> resolve
 Resolving package versions...
ERROR: The following package names could not be resolved:
 * TreeViews (0cdf7f9c-6f0a-11e8-33c6-7b5c10fffe5f in manifest but not in project)
Please specify by known `name=uuid`.
```
and if I edit Atom's REQUIRE to be `TreeViews=0cdf7f9c-6f0a-11e8-33c6-7b5c10fffe5f` I instead get:

```
(v0.7) pkg> resolve
 Resolving package versions...
ERROR: The following package names could not be resolved:
 * TreeViews=0cdf7f9c-6f0a-11e8-33c6-7b5c10fffe5f (not found in project, manifest or registry)
Please specify by known `name=uuid`.
```

Any hints?

**Comment by marius311** [comment]
OK, I got everything installed correctly now, and all inline evaluations still hang. 

I bisected it down to this commit which broke it for me: https://github.com/JunoLab/atom-julia-client/commit/a4f6f99916adafd2fdc7b566ea800abbf21fbd70

**Comment by pfitzseb** [comment]
Did you update ink (and are you on the 0.9 branch)? Also, did you `apm install` both Atom packages properly?

**Comment by marius311** [comment]
Between bisecting it and now, I built a slightly different 0.7 version, precompiled everything, and redid `apm install` per your suggestion (I thought I had remembered, but maybe not). Don't know what did it, but it seems to work now. Thanks!

**Comment by pfitzseb** [comment]
I hope to have a 0.6 and 0.7 compatible version of Juno out by the end of this week, so that should make the installation much more robust :)

**Comment by marius311** [comment]
> I hope to have a 0.6 and 0.7 compatible version of Juno out by the end of this week, so that should make the installation much more robust :)

That's great, much appreciate the work you guys have been doing on this! Its definitely starting to feel snappier and more robust.

**Comment by ChrisRackauckas** [comment]
```julia
(v0.7) pkg> up
  Updating registry at `C:\Users\Chris\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/JunoLab/Juno.jl.git`
  Updating git-repo `https://github.com/JunoLab/CodeTools.jl.git`
  Updating git-repo `https://github.com/JunoLab/Atom.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Atom [c52e3926]:
 Atom [c52e3926] log:
 ├─possible versions are: 0.6.15 or uninstalled
 ├─Atom [c52e3926] is fixed to version 0.6.15+
 └─restricted to versions 0.6.14 by an explicit requirement — no versions left
```

**Comment by pfitzseb** [comment]
Uhhh. Weird. 0.6.15 is for julia 0.6 only though, I'll tag the 0.7 beta releases in a bit.

**Comment by pfitzseb** [comment]
Update: https://discourse.julialang.org/t/ann-juno-0-7/12557
