### ISSUE TITLE
[BUG] Code formatting erases subscripts on operators

### ISSUE THREAD

**Issue by maikonaraujo** [JunoLab/Juno.jl#435]
Please search existing issues to avoid duplicates.

## Details
- Atom version: 1.39.0 x64
- Julia version: 1.2
- OS: Ubuntu
- Package versions:
  - Atom.jl:
  - julia-client:
  - ink:

### Steps to reproduce

1. Type a operator with a subscript:
2.0 |>ᵦ sin
2. Select the code and press Ctrl+J+F (format shortcut), it erases the beta subscript leaving:
2.0 |> sin

It is a problem when you implement an operator with a subscript and it get changed when you format your code.

Thanks,

**Comment by aviatesk** [comment]
I can't reproduce this. What version of Atom.jl are you using ?
Tell us back what `Julia-Client: Debug-Info` says.

![image](https://user-images.githubusercontent.com/40514306/69491362-6b596680-0ed7-11ea-8dd4-4a2966fbcf09.png)

**Comment by maikonaraujo** [comment]
# Atom:
Version: 1.39.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.2.0",
  "v8": "6.6.346.32",
  "uv": "1.20.3",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "64",
  "nghttp2": "1.29.0",
  "napi": "3",
  "openssl": "1.1.0h",
  "electron": "3.1.10",
  "chrome": "66.0.3359.181"
}
# julia-client:
Version: 0.11.3
Config:
{
  "firstBoot": false,
  "juliaOptions": {
    "startupArguments": [
      "-q"
    ]
  },
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true
  }
}


# ink:
Version: 0.11.6
Config:
undefined


# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}


# language-julia:
Version: 0.19.1
Config:
undefined


# language-weave:not installed


# indent-detective:
Version: 0.4.0
Config:
undefined


# latex-completions:
Version: 0.3.6
Config:
undefined


# versioninfo():
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_EDITOR = atom  -a
  JULIA_NUM_THREADS = 2

    Status `~/.julia/environments/v1.2/Project.toml`
  [c52e3926] Atom v0.11.3
  [e5e0dc1b] Juno v0.7.2

**Comment by maikonaraujo** [comment]
you just type something like +\_beta(tab) than format the code.

**Comment by aviatesk** [comment]
we internally use [JuliaFormatter](https://github.com/domluna/JuliaFormatter.jl) package, and maybe this bug is fixed within its latest releases.
Try
```jl
pkg> up
```
and then restart julia, and do the format.

**Comment by maikonaraujo** [comment]
Just updated as you suggested and same thing is still happening. It is not for all unicode, but when it is used as subscript on operators like: 
`+\_beta(tab)`
Thanks,

# Atom:
Version: 1.39.0
Dev Mode: false
Official Release: true
{
  "http_parser": "2.8.0",
  "node": "10.2.0",
  "v8": "6.6.346.32",
  "uv": "1.20.3",
  "zlib": "1.2.11",
  "ares": "1.14.0",
  "modules": "64",
  "nghttp2": "1.29.0",
  "napi": "3",
  "openssl": "1.1.0h",
  "electron": "3.1.10",
  "chrome": "66.0.3359.181"
}
# julia-client:
Version: 0.11.3
Config:
{
  "firstBoot": false,
  "juliaOptions": {
    "startupArguments": [
      "-q"
    ]
  },
  "uiOptions": {
    "enableMenu": true,
    "enableToolBar": true
  }
}


# ink:
Version: 0.11.7
Config:
undefined


# uber-juno:
Version: 0.3.0
Config:
{
  "disable": true
}


# language-julia:
Version: 0.19.2
Config:
undefined


# language-weave:not installed


# indent-detective:
Version: 0.4.0
Config:
undefined


# latex-completions:
Version: 0.3.6
Config:
undefined


# versioninfo():
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 2

    Status `~/.julia/environments/v1.2/Project.toml`
  [c52e3926] Atom v0.11.3
  [e5e0dc1b] Juno v0.7.2

**Comment by aviatesk** [comment]
what does
```jl
pkg> add JuliaFormatter
pkg> st
```
print ?

**Comment by maikonaraujo** [comment]
Just try the line below:
`+₁ +₂ +ₐ +₊`

```
(v1.2) pkg> st
    Status `~/.julia/environments/v1.2/Project.toml`
  [c52e3926] Atom v0.11.3
  [98e50ef6] JuliaFormatter v0.1.19
  [e5e0dc1b] Juno v0.7.2

```

**Comment by aviatesk** [comment]
ok, I figured out what happening 
[JuliaFormatter≥0.1.20 requires CSTParser≥1.0.0](https://github.com/domluna/JuliaFormatter.jl/pull/106), but the latest Atom still requires CSTParser≤0.6.3

This is resolved within our current master branch, so the quick fix for you is
```jl
pkg> add Atom#master
pkg> add Juno#master
pkg> add JuliaFormatter#master
```

***

We may bump Atom.jl version in the near future though.

**Comment by maikonaraujo** [comment]
That fixed the problem! Thanks!!
